### ISSUE TITLE
next() is reset after pause and resume

### ISSUE THREAD

**Issue by nkovacs** [fent/pauseable.js#2]
``` js
var pauseable = require('pauseable');
foo = p.setTimeout(function() {console.log('done')}, 10 * 1000);
```

wait a few seconds, then 

```
foo.pause();
foo.resume(), foo.next();
```

foo.next() will return 10000 and then start counting down from that.

**Comment by nkovacs** [comment]
It's still broken if you pause more than once.

**Comment by fent** [comment]
Can you give another example? It seems to work fine with this code I ran in the console

```
> var foo = p.setTimeout(function() { console.log('foo'); }, 100 * 1000);
undefined
> foo.pause();
95055
> foo.resume(); foo.next();
95055
> foo.pause();
93554
> foo.resume(); foo.next();
93554
```

**Comment by nkovacs** [comment]
https://github.com/nkovacs/pausetest

run bower install to download jquery, npm install to get pauseable and browserify. 
To build main.js run `node_modules/.bin/browserify main-src.js -o main.js`

Click start to start the countdown. Click pause once, wait, then click pause again to unpause. Then do it again. The countdown will jump back to a bigger value.

**Comment by fent** [comment]
Ok, I pushed a few changes, along with tests. tested with your repo too.
