### ISSUE TITLE
Clearing a timer inside of its callback breaks groups

### ISSUE THREAD

**Issue by Informatic** [fent/pauseable.js#30]
Hey.

I just discovered an intersting case.

If timer is cleared from inside of its handler, `_onDone`/`finished` callback (which I assume is not even public...?) gets called twice, which in case of timers bound to groups removes last timer from its list of managed timers.

https://github.com/fent/pauseable.js/blob/501d6ab629693975456e8246d652cc3fbeb258db/lib/index.js#L42
`indexOf` on second call here returns `-1` (since `id` has already been removed)
Wrapping this call with simple `if` to verify timer is still there seems to fix the problem, though, this should be properly handled in `timer` code - I'm not using intervals in my code, but it looks like interval cleared in its handler called after `interval.resume()` might get rescheduled as well. That would need a separate test, I guess...

Minimal testcase follows:
https://gist.github.com/81e656a7f06276081cf148283500c49e

**Comment by Informatic** [comment]
Just dropped a quick fix in my fork (and one that might fix additional untested issue I mentioned regarding intervals). Sadly I stumbled upon this bug during a very busy week so can't get proper tests done.
https://github.com/Informatic/pauseable.js/commit/e3b0b98d0a8a722f90e4b9071a4de661de447156

**Comment by fent** [comment]
thanks for the bug report! will push a fix out tonight
